services:
  - type: web
    name: gatepass-django
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python Gatepass/manage.py collectstatic --noinput
    startCommand: cd Gatepass && gunicorn hostel_gatepass.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: hostel_gatepass.settings

